platform :ios, "10.0"

use_frameworks! :linkage => :static

target "ReusableExtension_Example" do
  pod "ReusableExtension", :path => "../"
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "nuomi1"
end
