platform :ios, "8.0"
use_frameworks!

target "ReusableExtension_Example" do
  pod "ReusableExtension", :path => "../"
end

post_install do |installer|
  swift_4_0 = [
    "SpreadsheetView",
  ]

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if swift_4_0.include? target.name
        config.build_settings["SWIFT_VERSION"] = "4.0"
      end
    end
  end
end
