name: ReusableExtension

attributes:
  ORGANIZATIONNAME: nuomi1

targets:
  ReusableExtension_Example:
    type: application
    platform: iOS
    deploymentTarget: 9.0
    sources:
      - ReusableExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.cocoapods.demo.ReusableExtension-Example
        SWIFT_VERSION: 5.0
