name: ReusableExtension

targets:
  ReusableExtension_Example:
    type: application
    platform: iOS
    deploymentTarget: 8.0
    sources:
      - ReusableExtension
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        FRAMEWORK_SEARCH_PATHS: $(inherited)
        LIBRARY_SEARCH_PATHS: $(inherited)
        PRODUCT_BUNDLE_IDENTIFIER: org.cocoapods.demo.ReusableExtension-Example
        SWIFT_VERSION: 4.2
      configs:
        Debug:
          OTHER_SWIFT_FLAGS: $(inherited) -Xfrontend -warn-long-expression-type-checking=300 -Xfrontend -warn-long-function-bodies=300
